# site settings
title: SystemsFair
subtitle: SFU Surrey Engineering Career Fair
email: relmalla@sfu.ca
description: Software Systems and Mechatronic Systems Engineering Career Fair
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: "https://anjandev.gitlab.io" # the base hostname & protocol for your site
author: Ramy ElMallah
street_address: 250-13450 102 Avenue
city: Surrey
state: British Columbia
zip_code: V3T 0A3
country: Canada
phone: (604) 518-9051

# homepage tiles
tiles-source:  pages # accepts "posts" or "pages"
tiles-count: 5

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
